# 1. Le stockage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
# 2. Le déploiement (le container)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gauzian-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:alpine
        env:
        - name: POSTGRES_USER
          value: "mon_user"
        - name: POSTGRES_PASSWORD
          value: "mon_password"
        - name: POSTGRES_DB
          value: "gauzian_db"
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
# 3. Le service (pour que le backend puisse lui parler)
apiVersion: v1
kind: Service
metadata:
  name: db  # C'est ce nom que le backend utilisera dans l'URL
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP