# Configuration SonarQube self-hosted
# projectKey et projectName sont injectés via SONAR_SCANNER_OPTS dans chaque workflow

sonar.sources=app
sonar.exclusions=app/**/*.spec.*,node_modules/**,.nuxt/**,public/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
