# Configuration SonarCloud pour Gauzian Frontend

sonar.projectKey=visualAngus_gauzian
sonar.organization=visualangus
sonar.projectName=Gauzian Frontend

sonar.sources=app
sonar.exclusions=app/**/*.spec.*,node_modules/**,.nuxt/**,public/**

# Couverture de tests (à activer quand des tests seront ajoutés)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

