#!/bin/bash
# Script pour mettre à jour l'image backend et forcer le pull sur Clever Cloud

set -e

echo "🔨 Building backend image..."
docker build -f Dockerfile.backend.optimized -t angusvisual/gauzian-backend:latest .

echo "📤 Pushing to Docker Hub..."
docker push angusvisual/gauzian-backend:latest

echo "🔍 Getting image digest..."
docker pull angusvisual/gauzian-backend:latest > /dev/null 2>&1
DIGEST=$(docker inspect angusvisual/gauzian-backend:latest --format='{{index .RepoDigests 0}}')

echo "📝 Updating Dockerfile.backend.prebuilt with digest..."
cat > Dockerfile.backend.prebuilt <<EOF
# Auto-generated by update-backend-image.sh
# Digest: $DIGEST
FROM $DIGEST

ENV HOST=0.0.0.0
ENV PORT=8080

EXPOSE 8080

CMD ["./server"]
EOF

echo "✅ Done! Dockerfile.backend.prebuilt updated with:"
echo "   $DIGEST"
echo ""
echo "📌 Next steps:"
echo "   1. git add Dockerfile.backend.prebuilt"
echo "   2. git commit -m 'chore: Update backend image'"
echo "   3. git push origin main"
echo "   4. Restart on Clever Cloud"
