FROM rust:slim-bookworm

WORKDIR /app

# Installation des dépendances système + cargo-watch
RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    && cargo install cargo-watch \
    && rm -rf /var/lib/apt/lists/*

# Exposition du port
EXPOSE 3000

# Lancement en mode watch (recompile à chaque changement)
CMD ["cargo", "watch", "-x", "run"]
