use axum::{routing::{get, post}, Router};
use tower_http::trace::TraceLayer;

use crate::{handlers,metrics, state::AppState};

pub fn app(state: AppState) -> Router {
    Router::new()
        .route("/metrics", get(| | async { metrics::metrics_text() }))
        .route("/health/ready", get(handlers::health_check_handler))
        .route("/login", post(handlers::login_handler))
        .route("/register", post(handlers::register_handler))
        .route("/logout", post(handlers::logout_handler))
        .route("/protected", get(handlers::protected_handler))
        .route("/autologin", get(handlers::auto_login_handler))
        .route("/info", get(handlers::info_handler))
        .route("/drive/initialize_file", post(handlers::initialize_file_handler))
        .route("/drive/upload_chunk", post(handlers::upload_chunk_handler))
        
        .route("/drive/get_all_drive_info/{parent_id}", get(handlers::get_account_and_drive_info_handler))
        .route("/drive/create_folder", post(handlers::create_folder_handler))
        .route("/drive/get_file_folder/{parent_id}", get(handlers::get_file_folder_handler))
        .route("/drive/get_folder/{folder_id}", get(handlers::get_folder_handler))
        .route("/drive/file/{file_id}", get(handlers::get_file_info_handler))
        .route("/drive/download/{file_id}", get(handlers::download_file_handler))
        .route("/drive/finalize_upload/{file_id}/{etat}", post(handlers::finalize_upload_handler))
        .route("/drive/download_chunk/{s3_key}", get(handlers::download_chunk_handler))
        .route("/drive/folder_contents/{folder_id}", get(handlers::get_folder_contents_handler))
        .route("/drive/abort_upload", post(handlers::abort_upload_handler))
        .route("/drive/delete_file", post(handlers::delete_file_handler))
        .route("/drive/delete_folder", post(handlers::delete_folder_handler))
        .route("/drive/rename_file", post(handlers::rename_file_handler))
        .route("/drive/rename_folder", post(handlers::rename_folder_handler))
        .route("/drive/move_file", post(handlers::move_file_handler))
        .route("/drive/move_folder", post(handlers::move_folder_handler))
        .route("/drive/restore_file", post(handlers::restore_file_handler))
        .route("/drive/restore_folder", post(handlers::restore_folder_handler))
        .route("/drive/empty_trash", post(handlers::empty_trash_handler))
        .route("/drive/share_folder", post(handlers::share_folder_handler))
        .route("/drive/share_folder_batch", post(handlers::share_folder_batch_handler))
        .route("/drive/share_file", post(handlers::share_file_handler))
        .route("/drive/folder/{folder_id}/shared_users", get(handlers::get_folder_shared_users_handler))
        .route("/drive/propagate_file_access", post(handlers::propagate_file_access_handler))
        .route("/drive/propagate_folder_access", post(handlers::propagate_folder_access_handler))
        .route("/contacts/get_public_key/{email}", get(handlers::get_public_key_handler_by_email))
        .route("/drive/folder/{folder_id}/InfoItem", get(handlers::get_folder_info_item_handler))
        .route("/drive/file/{file_id}/InfoItem", get(handlers::get_file_info_item_handler))
        .route("/drive/revoke-access", post(handlers::revoke_access_handler))
        .layer(TraceLayer::new_for_http())
        .with_state(state)
}
